### ISSUE TITLE
Is there any way to get this library to leave the svg's stroke width property? 

### ISSUE THREAD

**Issue by HyruleanHero1988** [blueberryapps/react-svg-icon-generator#11]
I'm dynamically loading some icons in on a page. I would like to not have to specify stroke width as a prop, and instead let the stroke width be set on the icon itself, in the svg. However, every time I generate the Icon.js file, no matter what I try, it seems to strip the stroke-width property. Is there any way to keep the stroke width property in the svg?

**Comment by matejlauko** [comment]
The svg optimization strips the`stroke-width` and other strokexxx attributes, if you don't also specify `stroke` attribute, as it doesn't work by itself.
see: https://github.com/svg/svgo/blob/master/plugins/removeUselessStrokeAndFill.js#L44

If you set `stroke`, all others will be left like here: https://github.com/blueberryapps/react-svg-icon-generator/blob/master/examples/simple/components/Icon.js#L168
