### ISSUE TITLE
Publish package

### ISSUE THREAD

**Issue by nutgaard** [blueberryapps/react-svg-icon-generator#21]
#20 was recently merged, which updates the package to support newer versions of React.PropTypes.

The package needs to be published in order for people to take advantage of this change.

**Comment by eddiemcleanlux** [comment]
+1

**Comment by nutgaard** [comment]
Because I couldn't wait I've published a fork of this library; `react-svg-icon-generator-fork`
See repo here; https://github.com/nutgaard/react-svg-icon-generator/

**Comment by janmarsicek** [comment]
Hi @nutgaard sorry for inconvenience. Version 0.4.0 is available on NPM now https://www.npmjs.com/package/react-svg-icon-generator
