### ISSUE TITLE
Class attribute isn't converted to className

### ISSUE THREAD

**Issue by xemlock** [blueberryapps/react-svg-icon-generator#29]
In the output JSX `class` attributes aren't converted to `className`. This results in console warnings like: 
```
Warning: Unknown DOM property class. Did you mean className?
```

Tested in 0.4.0.

**Comment by janmarsicek** [comment]
Hey @xemlock 
could you please confirm it is still an issue? I guess it was already fixed with one of the new releases.

**Comment by xemlock** [comment]
Hi @janmarsicek,
You're right - the issue is now fixed. Thanks!
