### ISSUE TITLE
Invariant Violation: Element type is invalid for generated react-native icon

### ISSUE THREAD

**Issue by andyklimczak** [blueberryapps/react-svg-icon-generator#34]
I'm unable to load a generated Icon component using react native after importing the necessary imports (`Svg`, and `Path` from `expo`). I'm thinking that some further massaging of the generated react-native component is needed to react-nativeify it.

I have created a minimal repo for you that can reproduce the error using CRNA (contains a sample SVG in the `svg` folder): https://github.com/andyklimczak/icon-test

[This is the generated `Icon.js` component](https://github.com/andyklimczak/icon-test/blob/master/Icon.js). The modifications from what `icon-generator` generates is the `expo` import at the top and not using `radium`. The component was generated using: `svg-icon-generate --svgDir ./svg/ --destination ./Icon.js --native`

Here is the exception given when trying to run the react-native app on iOS:
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Icon`.

This error is located at:
    in RNSVGSvgView (at Svg.js:83)
    in Svg (at Icon.js:83)
    in Icon (at App.js:14)
    in RCTView (at View.js:60)
    in View (at App.js:9)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

throwOnInvalidElementType
    ReactNativeRenderer-dev.js:4706:4
createFiberFromElement
    ReactNativeRenderer-dev.js:4668:36
createChild
    ReactNativeRenderer-dev.js:7670:12
reconcileChildrenArray
    ReactNativeRenderer-dev.js:8014:10
reconcileChildrenAtExpirationTime
    ReactNativeRenderer-dev.js:8622:8
reconcileChildren
    ReactNativeRenderer-dev.js:8603:6
updateHostComponent
    ReactNativeRenderer-dev.js:9001:22
performUnitOfWork
    ReactNativeRenderer-dev.js:12924:25
workLoop
    ReactNativeRenderer-dev.js:12953:43
renderRoot
    ReactNativeRenderer-dev.js:12996:17
performWorkOnRoot
    ReactNativeRenderer-dev.js:13632:34
performWork
    ReactNativeRenderer-dev.js:13545:26
performSyncWork
    ReactNativeRenderer-dev.js:13506:16
requestWork
    ReactNativeRenderer-dev.js:13392:6
scheduleWorkImpl
    ReactNativeRenderer-dev.js:13259:24
scheduleRootUpdate
    ReactNativeRenderer-dev.js:13930:17
render
    ReactNativeRenderer-dev.js:14726:35
renderApplication
    renderApplication.js:49:21
runApplication
    AppRegistry.js:194:26
__callFunction
    MessageQueue.js:351:47
<unknown>
    MessageQueue.js:116:26
__guardSafe
    MessageQueue.js:314:6
callFunctionReturnFlushedQueue
    MessageQueue.js:115:17
```

Just wondering if anything obvious is popping out at you with what I did, thanks!

**Comment by janmarsicek** [comment]
Hi @andyklimczak 

I didn't have time to test it properly in Expo but apparently, there is no exported component `Path` from the `expo`.

Try to use destructuring to get the SVG components you need from Expo's SVG, e.g. 

```
import { Svg } from 'expo';

const { Path, Circle, Rect } = Svg;
```
Here is working Snack demo with your generated icon: https://snack.expo.io/ryuph0fPm Most likely you will need to modify your template for `Icon.js` to meet Expo's API for SVGs.

Let me know if it works and solves your problem 😉

**Comment by andyklimczak** [comment]
Oh fug, I see. I would have realized that if I had looked carefully at the `Svg.Circle` and `Svg.Rect` bit in expo's [svg example](https://docs.expo.io/versions/latest/sdk/svg). (I think I got hung up on `react-native-svg` imports or something)

The snack looks good, I'll give it a try in my real app and report back. Thanks so much!

**Comment by janmarsicek** [comment]
Let me know if it works for you.

Anyway, it's a good catch. We could add example/template nunjucks for Expo apps.

**Comment by andyklimczak** [comment]
Cool, this is working. Thank you for all of the help and spelling it out for me!
